package com.investigation.platform.audit.enums;

public enum AuditAction {
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_STATUS_CHANGED,
    USER_CREATED,
    USER_UPDATED,
    USER_INVITED,
    USER_DELETED,
    USER_STATUS_CHANGED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    PERMISSION_CHANGED,
    INTEGRATION_CREATED,
    INTEGRATION_UPDATED,
    INTEGRATION_DELETED,
    INTEGRATION_SYNCED,
    CONFIGURATION_CREATED,
    CONFIGURATION_UPDATED,
    FILE_UPLOADED,
    FILE_DELETED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT
}
