-- Complaint / Intake for Investigation (Step 15)
CREATE TABLE IF NOT EXISTS complaint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    complaint_key TEXT NOT NULL CHECK (complaint_key <> ''),
    investigation_id BIGINT REFERENCES investigation(id) ON DELETE SET NULL,
    integration_id BIGINT REFERENCES integrations(id) ON DELETE SET NULL,
    source_type TEXT NOT NULL CHECK (source_type IN ('MANUAL','INTEGRATION')),
    external_reference TEXT,
    title TEXT NOT NULL CHECK (title <> ''),
    description TEXT,
    batch_reference TEXT,
    raised_at TIMESTAMPTZ,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_complaint_org_key UNIQUE (org_id, complaint_key),
    CONSTRAINT uq_complaint_org_integration_external UNIQUE (org_id, integration_id, external_reference)
);
-- Partial unique to enforce one complaint per investigation (when associated)
CREATE UNIQUE INDEX IF NOT EXISTS uq_complaint_investigation ON complaint(investigation_id) WHERE investigation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_complaint_org ON complaint(org_id);
CREATE INDEX IF NOT EXISTS idx_complaint_org_investigation ON complaint(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_complaint_org_integration_external ON complaint(org_id, integration_id, external_reference);
