CREATE TABLE IF NOT EXISTS investigation_conclusion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    lifecycle TEXT NOT NULL DEFAULT 'DRAFT' CHECK (lifecycle IN ('DRAFT','FINAL')),
    outcome TEXT NOT NULL CHECK (outcome IN ('CONFIRMED','PARTIALLY_CONFIRMED','NOT_CONFIRMED','INCONCLUSIVE')),
    confidence TEXT CHECK (confidence IS NULL OR confidence IN ('LOW','MEDIUM','HIGH')),
    summary TEXT NOT NULL,
    investigator_reasoning TEXT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finalized_at TIMESTAMPTZ,
    CONSTRAINT uq_investigation_conclusion UNIQUE (org_id, investigation_id)
);

CREATE TABLE IF NOT EXISTS investigation_conclusion_finding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    conclusion_id BIGINT NOT NULL REFERENCES investigation_conclusion(id) ON DELETE CASCADE,
    finding_id BIGINT NOT NULL REFERENCES investigation_finding(id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL CHECK (relationship_type IN ('SUPPORTING','CONTRADICTING')),
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_conclusion_finding UNIQUE (org_id, conclusion_id, finding_id)
);

CREATE INDEX IF NOT EXISTS idx_investigation_conclusion_org_investigation ON investigation_conclusion(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_conclusion_finding_org_conclusion ON investigation_conclusion_finding(org_id, conclusion_id);
CREATE INDEX IF NOT EXISTS idx_conclusion_finding_org_investigation ON investigation_conclusion_finding(org_id, investigation_id);
