-- Investigation manual checks / checklist (Step 17) – investigator-owned verification, no AI
CREATE TABLE IF NOT EXISTS investigation_check (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (title <> ''),
    description TEXT,
    status TEXT NOT NULL CHECK (status IN ('OPEN','COMPLETED','SKIPPED')),
    result TEXT,
    notes TEXT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    completed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT chk_check_title_length CHECK (char_length(title) <= 200),
    CONSTRAINT chk_check_description_length CHECK (char_length(description) <= 2000),
    CONSTRAINT chk_check_result_length CHECK (char_length(result) <= 2000),
    CONSTRAINT chk_check_notes_length CHECK (char_length(notes) <= 5000)
);
CREATE INDEX IF NOT EXISTS idx_investigation_check_org_inv ON investigation_check(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_investigation_check_org_inv_status ON investigation_check(org_id, investigation_id, status);
