-- Investigation evidence linking (tenant-scoped association, no duplication of canonical fields)
CREATE TABLE IF NOT EXISTS investigation_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    canonical_evidence_id BIGINT NOT NULL REFERENCES canonical_evidence(id) ON DELETE CASCADE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_investigation_evidence UNIQUE (org_id, investigation_id, canonical_evidence_id)
);
CREATE INDEX IF NOT EXISTS idx_investigation_evidence_org_inv ON investigation_evidence(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_investigation_evidence_org_canonical ON investigation_evidence(org_id, canonical_evidence_id);

-- Investigator notes (append/update/delete, workspace data)
CREATE TABLE IF NOT EXISTS investigation_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    author_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL CHECK (content <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_note_content_length CHECK (char_length(content) <= 5000)
);
CREATE INDEX IF NOT EXISTS idx_investigation_note_org_inv ON investigation_note(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_investigation_note_org_inv_created ON investigation_note(org_id, investigation_id, created_at);
