-- Phase 7: Findings / Evidence Analysis
-- Tenant-scoped findings belonging to an Incident (Investigation persistence)
-- Minimal model: title, description, conclusion, status, timestamps, created_by

CREATE TABLE IF NOT EXISTS investigation_finding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (title <> ''),
    description TEXT,
    conclusion TEXT,
    status TEXT NOT NULL CHECK (status IN ('OPEN','CONFIRMED','DISMISSED')) DEFAULT 'OPEN',
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_finding_org_inv ON investigation_finding(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_finding_org_inv_status ON investigation_finding(org_id, investigation_id, status);

-- Evidence supporting a finding — tenant-safe, deduplicated
CREATE TABLE IF NOT EXISTS investigation_finding_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    finding_id BIGINT NOT NULL REFERENCES investigation_finding(id) ON DELETE CASCADE,
    canonical_evidence_id BIGINT NOT NULL REFERENCES canonical_evidence(id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL DEFAULT 'SUPPORTING' CHECK (relationship_type IN ('SUPPORTING','CONTRADICTING')),
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_finding_evidence UNIQUE (org_id, finding_id, canonical_evidence_id)
);

CREATE INDEX IF NOT EXISTS idx_finding_evidence_org_finding ON investigation_finding_evidence(org_id, finding_id);
CREATE INDEX IF NOT EXISTS idx_finding_evidence_org_evidence ON investigation_finding_evidence(org_id, canonical_evidence_id);

-- Optional check supporting a finding — tenant-safe
CREATE TABLE IF NOT EXISTS investigation_finding_check (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    finding_id BIGINT NOT NULL REFERENCES investigation_finding(id) ON DELETE CASCADE,
    check_id BIGINT NOT NULL REFERENCES investigation_check(id) ON DELETE CASCADE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_finding_check UNIQUE (org_id, finding_id, check_id)
);

CREATE INDEX IF NOT EXISTS idx_finding_check_org_finding ON investigation_finding_check(org_id, finding_id);
