CREATE TABLE IF NOT EXISTS investigation_evidence_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    canonical_evidence_id BIGINT NOT NULL REFERENCES canonical_evidence(id) ON DELETE CASCADE,
    reviewed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    review_status TEXT NOT NULL DEFAULT 'PENDING_REVIEW' CHECK (review_status IN ('PENDING_REVIEW','REVIEWED')),
    relevance TEXT CHECK (relevance IS NULL OR relevance IN ('RELEVANT','NOT_RELEVANT')),
    importance TEXT CHECK (importance IS NULL OR importance IN ('HIGH','MEDIUM','LOW')),
    assessment TEXT CHECK (assessment IS NULL OR assessment IN ('SUPPORTS_INVESTIGATION','CONTRADICTS_INVESTIGATION','CONTEXT_ONLY','INCONCLUSIVE','NOT_ASSESSED')),
    investigator_notes TEXT CHECK (investigator_notes IS NULL OR char_length(investigator_notes) <= 5000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT uq_evidence_assessment UNIQUE (org_id, investigation_id, canonical_evidence_id)
);

CREATE INDEX IF NOT EXISTS idx_evidence_assessment_org_investigation
    ON investigation_evidence_assessment(org_id, investigation_id);