-- Investigation decisions – investigator-authored conclusions (Step 19)
CREATE TABLE IF NOT EXISTS investigation_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id) ON DELETE CASCADE,
    decision_key TEXT NOT NULL CHECK (decision_key <> ''),
    title TEXT NOT NULL CHECK (title <> ''),
    conclusion TEXT NOT NULL CHECK (conclusion <> ''),
    rationale TEXT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_decision_key_length CHECK (char_length(decision_key) <= 100),
    CONSTRAINT chk_decision_title_length CHECK (char_length(title) <= 200),
    CONSTRAINT chk_decision_conclusion_length CHECK (char_length(conclusion) <= 5000),
    CONSTRAINT chk_decision_rationale_length CHECK (char_length(rationale) <= 5000),
    CONSTRAINT uq_decision_org_inv_key UNIQUE (org_id, investigation_id, decision_key)
);
CREATE INDEX IF NOT EXISTS idx_decision_org_inv ON investigation_decision(org_id, investigation_id);
CREATE INDEX IF NOT EXISTS idx_decision_org_inv_created ON investigation_decision(org_id, investigation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_decision_org_key ON investigation_decision(org_id, decision_key);
