-- Investigation table for minimal lifecycle DRAFT->ACTIVE->COMPLETED->ARCHIVED
-- Tenant-safe, unique investigation_key within org
CREATE TABLE IF NOT EXISTS investigation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organisations(org_id) ON DELETE CASCADE,
    investigation_key TEXT NOT NULL CHECK (investigation_key <> ''),
    title TEXT NOT NULL CHECK (title <> ''),
    description TEXT,
    status TEXT NOT NULL CHECK (status IN ('DRAFT','ACTIVE','COMPLETED','ARCHIVED')),
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_investigation_org_key UNIQUE (org_id, investigation_key)
);
CREATE INDEX IF NOT EXISTS idx_investigation_org ON investigation(org_id);
CREATE INDEX IF NOT EXISTS idx_investigation_org_status ON investigation(org_id, status);
